# Generated by Django 2.2.24 on 2021-12-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evangelisation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_message',
            field=models.ManyToManyField(help_text='Selectionner ceux qui vont recevoir le message', related_name='messages', to='evangelisation.Personne', verbose_name='Liste des personnes'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(help_text='Votre message', verbose_name='Description'),
        ),
    ]
